README.md
I often use the GitHub landing page, and the badge in there, to go to the docs page for any given project. I think it would be helpful.
If the "for-the-badge" [style](https://docs.readthedocs.io/en/stable/badges.html#style) is too flamboyant, please revert `0b0571d`.
=> Add Read the Docs badge

kbi/0004/index.rst
This is an excerpt from @jsheunis' answer on Neurostars (https://neurostars.org/t/using-datalad-for-managing-data-on-cluster/24494/2).
I think a lot of new datalad users will ask themselves the same question and it should be an FAQ-entry
=> KBI0004: FAQ: is it normal that files are moved to .git/annex/objects when converting existing data into a DataLad dataset?

kbi/0006/index.rst
This is a KBI that distills knowledge from https://github.com/psychoinformatics-de/studyforrest-data/issues/62.
Once merged, it fixes #20
=> Add a KBI on fixing location info in git-type special remotes

kbi/0001/index.rst
This adds a note that I wrote after one of the previous office hours, with information on how owner checks for the top-level directory introduced with Git v2.35.2 lead to error messages when cloning other people's datasets, and why setting the safe.directory config option is required to make it work (but also should be a conscious decision).
Essentially migrating this: https://github.com/psychoinformatics-de/datalad-officehours/issues/8 in to here.
Wasn't sure what the discussion link should be - this PR? or specifically created issue in this repo?
=> Add KBI0001 on shared git repositories

prototypes/generic.rst_
Fixes #35 
This PR adds a version tag to the knowledge base item prototype. This could help us to avoid confusion if a user uses a different dataset version than the version that was used during the crafting of a KBI.
Remark: we might have to revisit old KBIs in a few years in order to update the suggested command lines. The version tag could help us to identify possible candidates for such an update
=> Add a version-tag to KBI prototype

prototypes/generic.rst_
In its previous form the tag itself could be easily misintepreted as "version of the KBI".
The documentation now also declares a format to specify package-specific software versions.
=> `version` tag is meant to indicate a software version

kbi/0008/index.rst
This PR updates the commands that are used to remove the annex. Instead of manually removing files from `.git/annex`, and manually removing the `git-annex` branch, we use `git annex uninit` to remove them.
We use `git annex uninit` twice. The first execution removes the write-protection from `.git/annex/objects/*`, and allows the use of `rm -rf .git/annex/objects*`, to remove the annexed files. The second use of `git annex uninit` removes the `git-annex` branch and the `.git/annex`-directory.
=> improve annex artefact removal commands

kbi/0011/index.rst
This KBI comes from two separate reports that originated from personal communication (e-mails from 07 Nov 2022 and 24 Mar 2023), one of which has been recorded in https://github.com/psychoinformatics-de/datalad-officehours/issues/7
Since the underlying issue in both cases was a clash between multiple Python installations (once between Psychopy-bundled and regular on Windows, once between homebrew and conda on MacOS) that wasn't immediately visible, I thought it would make sense to write this KBI.
Both reports are summarized as examples, and a closer explanation for some diagnostic commands is provided.
=> Add KBI0011 (Debugging installation issues related to multiple Python versions)

kbi/0014/index.rst
In response to: https://github.com/psychoinformatics-de/knowledge-base/issues/49
=> KBI0014: pushing tags with datalad push

kbi/0013/index.rst
This is a start of a KBI for #28 using @mih's notes from https://github.com/datalad/datalad/issues/600#issuecomment-1059206527
Right now it only covers the use-case of splitting into multiple subdatasets. I plan to come back to this on my next support shift to explore adding a few other examples of how this workflow can be used.
=> KBI0013: Merge Data Availability Information

kbi/0012/index.rst
This short KBI is converted from my own notes. The origin was an issue on MacOS which was discussed during office hours at some point in March 2023 (and also demonstrated on our cluster).
=> Add KBI0012: annex encryption & GPG pinentry

kbi/0017/index.rst
A KBI that distills knowledge from https://github.com/psychoinformatics-de/knowledge-base/issues/65
It contains a recipe to delete a commit and to remove all annexed data that became unused due to deleting the commit
=> KBI0017: delete commits and their annexed data

kbi/0021/index.rst
Both presented solutions are partial, but presenting them as they are is the best way to close #24; other than forking / re-implementing a special remote.
The original support issue was continued in https://github.com/datalad-handbook/book/issues/941 which serves both as a tracking issue for the broader problem and an overview of the current state of the existing (not ours) special remote implementation. The KBI links to that issue.
=> 0021: Create a KBI on publishing to Zenodo

kbi/0022/index.rst
Short comparison of time for running `mv` vs `git mv`
Closes https://github.com/psychoinformatics-de/knowledge-base/issues/74
=> KBI0022: performance of mv vs git mv

kbi/0023/index.rst
This KBI covers keyring configuration in the context of a problem with credential retrieval observed on a headless system. It also provides a general overview of keyring access.
Closes #85
=> 0023: Add a KBI on keyring config

kbi/0026/index.rst
This KBI is an attempt to document some of the knowledge gathered in #15, and point out that shortcomings of datalad configs in core can be fixed by using next. It is still a bit vague for my liking, but I struggled with finding a better way - maybe this can be shaped further in the next user support session.
It addresses parts of #15.
=> Add a KBI with insights from #15 on config overrides

kbi/0007/index.rst, kbi/0028/index.rst, kbi/0028/list_files.py
It did not come up as a support event (i.e. "nobody asked for this"), but this goes back to something we considered for an archival request (internal issue tracker) and something I later explored for myself, so I think knowledge base is an useful place to document that with better visibility.
Features Nextcloud / Sciebo specific details, and a practical example of an uncurl remote. Writing it up was very educational for me.
=> KBI0028: Notes on Sciebo/Nextcloud share URLs

kbi/0029/index.rst
A write-up demonstrating how to create an empty RIA store by hand or with the helper function `create_store` in `datalad/customremotes/ria_utils.py`.
Closes #91
=> KBI 0029: Create an empty RIA store

LICENSE, conf.py
This PR proposes licensing the Knowledge Base repo under CC-BY license. License text is added, and copyright note in Sphinx conf is updated (unfortunately I found no easy way to display it as link - see commit message). When merged, would close #117 
Note that compared to the DataLad Handbook (which is licensed under CC-BY-SA) this license omits the ShareAlike clause, but I currently don't see the need to make the licenses identical.
I would appreciate explicit approvals (or dissents).
=> Add CC-BY License

kbi/0032/index.rst
DataLad-next 1.4 patches most of the RIA code, improving it in many aspects. One particular improvement is related to a `stat` command error when pushing from macOS to linux. That error has been reported several times in different places (GitHub issue tracker, Neurostars, office hour).
This KBI is a rephrasing of my post in a [Neurostars thread](https://neurostars.org/t/datalad-push-to-ria-storage-not-working/29049). I wrote that post mostly to provide a reference to the changes for future visitors looking for an answer (the response is 2 months older than the question, asked before the RIA fixes were released). The answer is now repeated here, to provide a persistent record in a place controlled by us (in terms of availability) -- granted, Neurostars is a friendly and trustworthy place …
=> Add KBI on RIA store improvements in -next

conf.py
In an email to maintainers of affected projects, readthedocs advised to make configuration changes ahead of the deprecation of injecting Sphinx- related configurations during build time.
For more info, see: https://about.readthedocs.com/blog/2024/07/addons-by-default/
=> Add RTD-recommended configuration ahead of deprecations

kbi/0001/index.rst
see https://git-scm.com/docs/git-config#Documentation/git-config.txt-safedirectory
=> mention safe.directory path matching available with 2.46+

kbi/0023/index.rst
This introduces a small restructuring and extension of KBI0023: Keyring configuration to address a recently observed case where the encrypted file keyring was used in the base environment but not a virtual environment, due to (un)availability of PyCryptodome.
- moved the `datalad wtf --section credentials` example higher; now it is part of the introduction, before problems are described
- added an information about listing backends with keyring's CLI
- explained SecretService, EncryptedKeyring, and PlaintextKeyring which are likely to come into play
- there are now two problems with separate subheadings; one old (SecretService), one new (EncryptedKeyring)
- added a new user solution, explaining that EncryptedKeyring requires PyCryptodome, which may not get installed automatically in …
=> Add more information about keyring backends & dependencies
